package com.example.allokgames.pokemongame;

/**
 * Created by Галимзянов Газинур on 15.04.2016.
 */
public class Pichu extends Pokemon {
    Pichu(){
        this.pok="pichu";
        this.type1="Thunder";
        this.exp=0;
        this.spd=60;
        this.maxexp=200;
        this.hp=20;
        this.maxhp=20;
        this.atk=40;
        this.happiness=70;
        this.energy=100;
        this.satiety=100;
        this.firsty=100;
        this.maxhpup=2;
        this.spdup=2;
        this.atkup=1;
        this.defup=1;
        this.maxfirsty=100;
        this.maxenergy=100;
        this.def=15;
        this.lvl=5;
        this.name="pichu";
        this.maxsatiety=100;
    }
    Pichu(String name){
        this.pok="pichu";
        this.type1="Thunder";
        this.exp=0;
        this.maxhpup=2;
        this.spdup=1;
        this.atkup=1;
        this.defup=1;
        this.spd=60;
        this.maxexp=200;
        this.hp=20;
        this.maxhp=20;
        this.atk=40;
        this.happiness=70;
        this.energy=100;
        this.satiety=100;
        this.firsty=100;
        this.maxfirsty=100;
        this.maxenergy=100;
        this.def=15;
        this.lvl=5;
        this.name=name;
        this.maxsatiety=100;
    }
    Pichu(short spd, int exp, short maxexp, short hp, short maxhp, short atk, short happiness, short maxenergy, short maxsatiety, short firsty, short maxfirsty, short energy, short def, short lvl, String name, short satiety){
        this.exp=exp;
        this.pok="pichu";
        this.spd=spd;
        this.maxexp=maxexp;
        this.hp=hp;
        this.maxhpup=2;
        this.spdup=1;
        this.atkup=1;
        this.defup=1;
        this.maxhp=maxhp;
        this.atk=atk;
        this.happiness=happiness;
        this.energy=energy;
        this.satiety=satiety;
        this.firsty=firsty;
        this.maxfirsty=maxfirsty;
        this.maxenergy=maxenergy;
        this.def=def;
        this.lvl=lvl;
        this.name=name;
        this.maxsatiety=maxsatiety;
        this.type1="Thunder";}
}
